export const assets = {
  logo: "/logo.jpg",
  logoMark: "/logo-mark.png",
  heroPortrait: "/coach-portrait.jpg",
  aboutPortrait: "/coach-portrait.jpg",
  heroBackground: "/logo-mark.png",
  coachingHero: "/coach-portrait.jpg",
  workshopHero: "/coach-portrait.jpg",
  ogImage: "/og-image.jpg",
  favicon: "/favicon.png",
  appleTouchIcon: "/apple-touch-icon.png",
  icon192: "/icon-192.png",
  icon512: "/icon-512.png",
  masterLogo: "/whitebeardwisdom_logo.jpg",
} as const;
